// Generated by pkmntcg tools/gen_vanilla_twinleaf.py from official card text
// (Limitless TCG): vanilla pool printings Twinleaf didn't have.
import { PokemonCard } from '../../../game/store/card/pokemon-card';
import { Stage, CardType } from '../../../game/store/card/card-types';

export class ChikoritaMEPPool extends PokemonCard {
  public stage: Stage = Stage.BASIC;
  public cardType: CardType[] = [G];
  public hp: number = 70;
  public weakness = [{ type: R }];
  public resistance = [];
  public retreat = [C];
  public attacks = [{ name: "Razor Leaf", cost: [G, C], damage: 30, text: '' }];
  public regulationMark = "J";
  public set: string = 'MEP';
  public setNumber: string = '46';
  public cardImage: string = 'assets/cardback.png';
  public name: string = "Chikorita";
  public fullName: string = "Chikorita MEP 46";
}

export class GrookeyMEPPool extends PokemonCard {
  public stage: Stage = Stage.BASIC;
  public cardType: CardType[] = [G];
  public hp: number = 70;
  public weakness = [{ type: R }];
  public resistance = [];
  public retreat = [C];
  public attacks = [{ name: "Branch Poke", cost: [G, G], damage: 40, text: '' }];
  public regulationMark = "J";
  public set: string = 'MEP';
  public setNumber: string = '52';
  public cardImage: string = 'assets/cardback.png';
  public name: string = "Grookey";
  public fullName: string = "Grookey MEP";
}
