// Generated by pkmntcg tools/gen_vanilla_twinleaf.py from official card text
// (Limitless TCG): vanilla pool printings Twinleaf didn't have.
import { PokemonCard } from '../../../game/store/card/pokemon-card';
import { Stage, CardType, CardTag } from '../../../game/store/card/card-types';

export class TeamRocketsHoundourDRIPool extends PokemonCard {
  public stage: Stage = Stage.BASIC;
  protected _tags = [CardTag.TEAM_ROCKET];
  public cardType: CardType[] = [R];
  public hp: number = 70;
  public weakness = [{ type: W }];
  public resistance = [];
  public retreat = [C];
  public attacks = [{ name: "Steady Firebreathing", cost: [R], damage: 20, text: '' }];
  public regulationMark = "I";
  public set: string = 'DRI';
  public setNumber: string = '37';
  public cardImage: string = 'assets/cardback.png';
  public name: string = "Team Rocket's Houndour";
  public fullName: string = "Team Rocket's Houndour DRI";
}
