// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../../game/store/card/pokemon-card';
import { Stage, CardType, CardTag } from '../../../game/store/card/card-types';
import { PowerType, StoreLike, State, StateUtils } from '../../../game';
import { PutDamageEffect } from '../../../game/store/effects/attack-effects';
import { Effect } from '../../../game/store/effects/effect';
import { IS_ABILITY_BLOCKED } from '../../../game/store/prefabs/prefabs';
import { SURVIVE_ON_TEN_ON_COIN_FLIP } from '../../../game/store/prefabs/effect-of-attack-prefabs';

export class Hariyama extends PokemonCard {
  protected _tags = [CardTag.SINGLE_STRIKE];
  public stage: Stage = Stage.STAGE_1;
  public evolvesFrom: string = 'Makuhita';
  public cardType: CardType[] = [F];
  public hp: number = 140;
  public weakness = [{ type: P }];
  public retreat = [C, C, C, C];

  public powers = [
    {
      name: 'Guts',
      powerType: PowerType.ABILITY,
      text: 'If this Pokémon would be Knocked Out by damage from an attack, flip a coin. If heads, this Pokémon is not Knocked Out, and its remaining HP becomes 10.',
    },
  ];

  public attacks = [
    {
      name: 'Hammer In',
      cost: [F, C, C],
      damage: 100,
      text: '',
    },
  ];

  public regulationMark: string = 'E';

  public set: string = 'FST';
  public setNumber: string = '143';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Hariyama';
  public fullName: string = 'Hariyama FST 143';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Ability: Guts (passive - survive KO on coin flip)
    // Ref: set-burning-shadows/heracross.ts (Guts - PutDamageEffect + surviveOnTenHPReason)
    if (effect instanceof PutDamageEffect && effect.target.cards.includes(this)) {
      const pokemonCard = effect.target.getPokemonCard();
      if (pokemonCard !== this) {
        return state;
      }

      const player = StateUtils.findOwner(state, effect.target);

      if (IS_ABILITY_BLOCKED(store, state, player, this)) {
        return state;
      }

      SURVIVE_ON_TEN_ON_COIN_FLIP(store, state, effect, player, this.powers[0].name);
    }

    return state;
  }
}
