// Generated by pkmntcg tools/gen_vanilla_twinleaf.py from official card text
// (Limitless TCG): vanilla pool printings Twinleaf didn't have.
import { PokemonCard } from '../../../game/store/card/pokemon-card';
import { Stage, CardType } from '../../../game/store/card/card-types';

export class MinccinoJTGPool extends PokemonCard {
  public stage: Stage = Stage.BASIC;
  public cardType: CardType[] = [C];
  public hp: number = 70;
  public weakness = [{ type: F }];
  public resistance = [];
  public retreat = [C];
  public attacks = [{ name: "Slap", cost: [C], damage: 20, text: '' }];
  public regulationMark = "H";
  public set: string = 'JTG';
  public setNumber: string = '125';
  public cardImage: string = 'assets/cardback.png';
  public name: string = "Minccino";
  public fullName: string = "Minccino JTG";
}
