// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { TrainerCard } from '../../../game/store/card/trainer-card';
import { TrainerType } from '../../../game/store/card/card-types';
import { StoreLike, State, GameError, GameMessage, PlayerType, ChoosePokemonPrompt } from '../../../game';
import { Effect } from '../../../game/store/effects/effect';
import { HealEffect } from '../../../game/store/effects/game-effects';
import { SlotType } from '../../../game/store/actions/play-card-action';
import { CardTarget } from '../../../game/store/actions/play-card-action';
import { WAS_TRAINER_USED } from '../../../game/store/prefabs/trainer-prefabs';

export class PokemonCenterLady extends TrainerCard {
  public trainerType: TrainerType = TrainerType.SUPPORTER;
  public set: string = 'FLF';
  public setNumber: string = '93';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Pokémon Center Lady';
  public fullName: string = 'Pokémon Center Lady FLF';
  public text: string = 'Heal 60 damage and remove all Special Conditions from 1 of your Pokémon. You may play only 1 Supporter card during your turn (before your attack).';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Refs: set-cosmic-eclipse/mallow-and-lana.ts (supporter heal pattern), set-perfect-order/lumiose-galette.ts (heal + condition removal)
    if (WAS_TRAINER_USED(effect, this)) {
      const player = effect.player;

      // A Trainer can't be played for no effect: some Pokémon must have damage or a Special Condition
      let canHeal = false;
      player.forEachPokemon(PlayerType.BOTTOM_PLAYER, cardList => {
        if (cardList.damage > 0 || cardList.specialConditions.length > 0) {
          canHeal = true;
        }
      });
      if (!canHeal) {
        throw new GameError(GameMessage.CANNOT_PLAY_THIS_CARD);
      }

      // A Pokémon with no damage counters and no Special Condition has nothing to heal and can't be chosen
      // (Advanced Rulebook C-06; ruling 43)
      const blocked: CardTarget[] = [];
      player.forEachPokemon(PlayerType.BOTTOM_PLAYER, (cardList, card, target) => {
        if (cardList.damage === 0 && cardList.specialConditions.length === 0) {
          blocked.push(target);
        }
      });

      return store.prompt(state, new ChoosePokemonPrompt(
        player.id,
        GameMessage.CHOOSE_POKEMON_TO_HEAL,
        PlayerType.BOTTOM_PLAYER,
        [SlotType.ACTIVE, SlotType.BENCH],
        { min: 1, max: 1, allowCancel: false, blocked }
      ), targets => {
        if (targets && targets.length > 0) {
          const target = targets[0];

          // Heal 60 damage
          const healEffect = new HealEffect(player, target, 60);
          store.reduceEffect(state, healEffect);

          // Remove all Special Conditions
          target.specialConditions = [];
        }
      });
    }

    return state;
  }
}
