// Generated by pkmntcg tools/gen_vanilla_twinleaf.py from official card text
// (Limitless TCG): vanilla pool printings Twinleaf didn't have.
import { PokemonCard } from '../../../game/store/card/pokemon-card';
import { Stage, CardType } from '../../../game/store/card/card-types';

export class SlowpokePREPool extends PokemonCard {
  public stage: Stage = Stage.BASIC;
  public cardType: CardType[] = [W];
  public hp: number = 70;
  public weakness = [{ type: L }];
  public resistance = [];
  public retreat = [C, C];
  public attacks = [{ name: "Water Gun", cost: [W], damage: 10, text: '' }, { name: "Tail Whap", cost: [W, C], damage: 30, text: '' }];
  public regulationMark = "H";
  public set: string = 'PRE';
  public setNumber: string = '18';
  public cardImage: string = 'assets/cardback.png';
  public name: string = "Slowpoke";
  public fullName: string = "Slowpoke PRE";
}

export class BunearyPREPool extends PokemonCard {
  public stage: Stage = Stage.BASIC;
  public cardType: CardType[] = [C];
  public hp: number = 60;
  public weakness = [{ type: F }];
  public resistance = [];
  public retreat = [C];
  public attacks = [{ name: "Smash Kick", cost: [C], damage: 20, text: '' }];
  public regulationMark = "H";
  public set: string = 'PRE';
  public setNumber: string = '83';
  public cardImage: string = 'assets/cardback.png';
  public name: string = "Buneary";
  public fullName: string = "Buneary PRE";
}

export class NoibatPREPool extends PokemonCard {
  public stage: Stage = Stage.BASIC;
  public cardType: CardType[] = [C];
  public hp: number = 60;
  public weakness = [{ type: L }];
  public resistance = [{ type: F, value: -30 }];
  public retreat = [C];
  public attacks = [{ name: "Flap", cost: [C], damage: 20, text: '' }];
  public regulationMark = "H";
  public set: string = 'PRE';
  public setNumber: string = '90';
  public cardImage: string = 'assets/cardback.png';
  public name: string = "Noibat";
  public fullName: string = "Noibat PRE";
}
