// Generated by pkmntcg tools/gen_vanilla_twinleaf.py from official card text
// (Limitless TCG): vanilla pool printings Twinleaf didn't have.
import { PokemonCard } from '../../../game/store/card/pokemon-card';
import { Stage, CardType } from '../../../game/store/card/card-types';

export class CharcadetSCRPool extends PokemonCard {
  public stage: Stage = Stage.BASIC;
  public cardType: CardType[] = [R];
  public hp: number = 70;
  public weakness = [{ type: W }];
  public resistance = [];
  public retreat = [C];
  public attacks = [{ name: "Flare", cost: [R, C], damage: 30, text: '' }];
  public regulationMark = "H";
  public set: string = 'SCR';
  public setNumber: string = '29';
  public cardImage: string = 'assets/cardback.png';
  public name: string = "Charcadet";
  public fullName: string = "Charcadet SCR";
}

export class FroakieSCRPool extends PokemonCard {
  public stage: Stage = Stage.BASIC;
  public cardType: CardType[] = [W];
  public hp: number = 60;
  public weakness = [{ type: L }];
  public resistance = [];
  public retreat = [C];
  public attacks = [{ name: "Rain Splash", cost: [W, C], damage: 20, text: '' }];
  public regulationMark = "H";
  public set: string = 'SCR';
  public setNumber: string = '39';
  public cardImage: string = 'assets/cardback.png';
  public name: string = "Froakie";
  public fullName: string = "Froakie SCR";
}

export class FrogadierSCRPool extends PokemonCard {
  public stage: Stage = Stage.STAGE_1;
  public evolvesFrom = "Froakie";
  public cardType: CardType[] = [W];
  public hp: number = 90;
  public weakness = [{ type: L }];
  public resistance = [];
  public retreat = [C];
  public attacks = [{ name: "Wave Splash", cost: [W, C], damage: 40, text: '' }];
  public regulationMark = "H";
  public set: string = 'SCR';
  public setNumber: string = '40';
  public cardImage: string = 'assets/cardback.png';
  public name: string = "Frogadier";
  public fullName: string = "Frogadier SCR";
}

export class FlittleSCRPool extends PokemonCard {
  public stage: Stage = Stage.BASIC;
  public cardType: CardType[] = [P];
  public hp: number = 50;
  public weakness = [{ type: D }];
  public resistance = [{ type: F, value: -30 }];
  public retreat = [C];
  public attacks = [{ name: "Peck", cost: [P], damage: 10, text: '' }];
  public regulationMark = "H";
  public set: string = 'SCR';
  public setNumber: string = '68';
  public cardImage: string = 'assets/cardback.png';
  public name: string = "Flittle";
  public fullName: string = "Flittle SCR";
}

export class RioluSCRPool extends PokemonCard {
  public stage: Stage = Stage.BASIC;
  public cardType: CardType[] = [F];
  public hp: number = 70;
  public weakness = [{ type: P }];
  public resistance = [];
  public retreat = [C];
  public attacks = [{ name: "Punch", cost: [F, C], damage: 30, text: '' }];
  public regulationMark = "H";
  public set: string = 'SCR';
  public setNumber: string = '81';
  public cardImage: string = 'assets/cardback.png';
  public name: string = "Riolu";
  public fullName: string = "Riolu SCR";
}
