// Generated by pkmntcg tools/gen_vanilla_twinleaf.py from official card text
// (Limitless TCG): vanilla pool printings Twinleaf didn't have.
import { PokemonCard } from '../../../game/store/card/pokemon-card';
import { Stage, CardType } from '../../../game/store/card/card-types';

export class TimburrBLKPool extends PokemonCard {
  public stage: Stage = Stage.BASIC;
  public cardType: CardType[] = [F];
  public hp: number = 70;
  public weakness = [{ type: P }];
  public resistance = [];
  public retreat = [C, C];
  public attacks = [{ name: "Low Kick", cost: [F], damage: 10, text: '' }, { name: "Strength", cost: [F, C, C], damage: 50, text: '' }];
  public regulationMark = "I";
  public set: string = 'BLK';
  public setNumber: string = '47';
  public cardImage: string = 'assets/cardback.png';
  public name: string = "Timburr";
  public fullName: string = "Timburr BLK";
}

export class VullabyWHTPool extends PokemonCard {
  public stage: Stage = Stage.BASIC;
  public cardType: CardType[] = [D];
  public hp: number = 70;
  public weakness = [{ type: L }];
  public resistance = [{ type: F, value: -30 }];
  public retreat = [C];
  public attacks = [{ name: "Playful Kick", cost: [C], damage: 10, text: '' }];
  public regulationMark = "I";
  public set: string = 'WHT';
  public setNumber: string = '63';
  public cardImage: string = 'assets/cardback.png';
  public name: string = "Vullaby";
  public fullName: string = "Vullaby WHT";
}
